### ISSUE TITLE
Setting a "filter" attribute in a <v:img> tag results in 500 error

### ISSUE THREAD

**Issue by romcart** [actionverb/vae_remote#15]
Using a filter attribute in a <v:img> tag will result in a 500 error.

Example: 
`<v:img path="image" image_size="cover" filter="grey" />` <--- 500 error
`<v:img path="image" image_size="cover" filter="reflect(10%)" />` <--- 500 error
`<v:img path="image" image_size="cover" filter="" />` <--- no problem

**Comment by bombino** [comment]
Resolved in #16
