### ISSUE TITLE
The store:cart:updated event fires twice when removing an item from cart

### ISSUE THREAD

**Issue by romcart** [actionverb/vae_remote#3]
I reproduced by adding the following to __vae.php:

```
vae_register_hook("store:cart:updated", 'cartUpdated');

function cartUpdated() {
  error_log('*** cart was updated ***');
}
```

When an item is _added_ to a cart, the event fires once as expected. But when you _remove_ an item from a cart, it fires twice.

**Comment by bombino** [comment]
How are you removing the item from the cart?
