### ISSUE TITLE
The store:add_to_cart event doesn't fire when adding an item to the cart using vae_store_add_item_to_cart()

### ISSUE THREAD

**Issue by romcart** [actionverb/vae_remote#4]
The event fires when adding to a cart with the `<v:store:add_to_cart>` VaeML tag, but not when using the vae_store_add_item_to_cart() PHP function.

**Comment by bombino** [comment]
That's correct.  Tag-based events only fire when the tag uses.  I recommend using a wrapper function around your use of the PHP function to handle whatever you would have put in the hook.
